config/routes.rb
Blazer::Engine.routes.draw do
  resources :queries do
    post :run, on: :collection # err on the side of caution
    post :cancel, on: :collection
    post :refresh, on: :member
    get :tables, on: :collection
    get :schema, on: :collection
    get :docs, on: :collection
  end

  resources :checks, except: [:show] do
    get :run, on: :member
  end

  resources :dashboards, except: [:index] do
    post :refresh, on: :member
  end

  root to: "queries#home"
end

app/models/blazer/audit.rb
module Blazer
  class Audit < Record
    belongs_to :user, optional: true, class_name: Blazer.user_class.to_s
    belongs_to :query, optional: true
  end
end

app/models/blazer/check.rb
module Blazer
  class Check < Record
    belongs_to :creator, optional: true, class_name: Blazer.user_class.to_s if Blazer.user_class
    belongs_to :query

    validates :query_id, presence: true
    validate :validate_emails
    validate :validate_variables, if: -> { query_id_changed? }

    before_validation :set_state
    before_validation :fix_emails

    def split_emails
      emails.to_s.downcase.split(",").map(&:strip)
    end

    def split_slack_channels
      if Blazer.slack?
        slack_channels.to_s.downcase.split(",").map(&:strip)
      else
        []
      end
    end

    def update_state(result)
      check_type =
        if respond_to?(:check_type)
          self.check_type
        elsif respond_to?(:invert)
          invert ? "missing_data" : "bad_data"
        else
          "bad_data"
        end

      message = result.error

      self.state =
        if result.timed_out?
          "timed out"
        elsif result.error
          "error"
        elsif check_type == "anomaly"
          anomaly, message = result.detect_anomaly
          if anomaly.nil?
            "error"
          elsif anomaly
            "failing"
          else
            "passing"
          end
        elsif result.rows.any?
          check_type == "missing_data" ? "passing" : "failing"
        else
          check_type == "missing_data" ? "failing" : "passing"
        end

      self.last_run_at = Time.now if respond_to?(:last_run_at=)
      self.message = message if respond_to?(:message=)

      if respond_to?(:timeouts=)
        if result.timed_out?
          self.timeouts += 1
          self.state = "disabled" if timeouts >= 3
        else
          self.timeouts = 0
        end
      end

      # do not notify on creation, except when not passing
      if (state_was != "new" || state != "passing") && state != state_was
        Blazer::CheckMailer.state_change(self, state, state_was, result.rows.size, message, result.columns, result.rows.first(10).as_json, result.column_types, check_type).deliver_now if emails.present?
        Blazer::SlackNotifier.state_change(self, state, state_was, result.rows.size, message, check_type)
      end
      save! if changed?
    end

    private

      def set_state
        self.state ||= "new"
      end

      def fix_emails
        # some people like doing ; instead of ,
        # but we know what they mean, so let's fix it
        # also, some people like to use whitespace
        if emails.present?
          self.emails = emails.strip.gsub(/[;\s]/, ",").gsub(/,+/, ", ")
        end
      end

      def validate_emails
        unless split_emails.all? { |e| e =~ /\A\S+@\S+\.\S+\z/ }
          errors.add(:base, "Invalid emails")
        end
      end

      def validate_variables
        if query.variables.any?
          errors.add(:base, "Query can't have variables")
        end
      end
  end
end

app/models/blazer/connection.rb
module Blazer
  class Connection < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/blazer/dashboard.rb
module Blazer
  class Dashboard < Record
    belongs_to :creator, optional: true, class_name: Blazer.user_class.to_s if Blazer.user_class
    has_many :dashboard_queries, dependent: :destroy
    has_many :queries, through: :dashboard_queries

    validates :name, presence: true

    def to_param
      [id, name.gsub("'", "").parameterize].join("-")
    end
  end
end

app/models/blazer/dashboard_query.rb
module Blazer
  class DashboardQuery < Record
    belongs_to :dashboard
    belongs_to :query

    validates :dashboard_id, presence: true
    validates :query_id, presence: true
  end
end

app/models/blazer/query.rb
module Blazer
  class Query < Record
    belongs_to :creator, optional: true, class_name: Blazer.user_class.to_s if Blazer.user_class
    has_many :checks, dependent: :destroy
    has_many :dashboard_queries, dependent: :destroy
    has_many :dashboards, through: :dashboard_queries
    has_many :audits

    validates :statement, presence: true

    scope :named, -> { where("blazer_queries.name <> ''") }

    def to_param
      [id, name].compact.join("-").gsub("'", "").parameterize
    end

    def friendly_name
      name.to_s.sub(/\A[#\*]/, "").gsub(/\[.+\]/, "").strip
    end

    def viewable?(user)
      if Blazer.query_viewable
        Blazer.query_viewable.call(self, user)
      else
        true
      end
    end

    def editable?(user)
      editable = !persisted? || (name.present? && name.first != "*" && name.first != "#") || user == try(:creator)
      editable &&= viewable?(user)
      editable &&= Blazer.query_editable.call(self, user) if Blazer.query_editable
      editable
    end

    def variables
      Blazer.extract_vars(statement)
    end
  end
end

app/models/blazer/record.rb
module Blazer
  class Record < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/blazer/base_controller.rb
module Blazer
  class BaseController < ApplicationController
    # skip filters
    filters = _process_action_callbacks.map(&:filter) - [:activate_authlogic]
    skip_before_action(*filters, raise: false)
    skip_after_action(*filters, raise: false)
    skip_around_action(*filters, raise: false)

    protect_from_forgery with: :exception

    if ENV["BLAZER_PASSWORD"]
      http_basic_authenticate_with name: ENV["BLAZER_USERNAME"], password: ENV["BLAZER_PASSWORD"]
    end

    if Blazer.settings["before_action"]
      raise Blazer::Error, "The docs for protecting Blazer with a custom before_action had an incorrect example from August 2017 to June 2018. The example method had a boolean return value. However, you must render or redirect if a user is unauthorized rather than return a falsy value. Double check that your before_action works correctly for unauthorized users (if it worked when added, there should be no issue). Then, change before_action to before_action_method in config/blazer.yml."
    end

    if Blazer.before_action
      before_action Blazer.before_action.to_sym
    end

    if Blazer.override_csp
      after_action do
        response.headers['Content-Security-Policy'] = "default-src 'self' https: 'unsafe-inline' 'unsafe-eval' data:"
      end
    end

    layout "blazer/application"

    private

      def process_vars(statement, data_source)
        (@bind_vars ||= []).concat(Blazer.extract_vars(statement)).uniq!
        @bind_vars.each do |var|
          params[var] ||= Blazer.data_sources[data_source].variable_defaults[var]
        end
        @success = @bind_vars.all? { |v| params[v] }

        if @success
          @bind_vars.each do |var|
            value = params[var].presence
            if value
              if ["start_time", "end_time"].include?(var)
                value = value.to_s.gsub(" ", "+") # fix for Quip bug
              end

              if var.end_with?("_at")
                begin
                  value = Blazer.time_zone.parse(value)
                rescue
                  # do nothing
                end
              end

              if value =~ /\A\d+\z/
                value = value.to_i
              elsif value =~ /\A\d+\.\d+\z/
                value = value.to_f
              end
            end
            value = Blazer.transform_variable.call(var, value) if Blazer.transform_variable
            statement.gsub!("{#{var}}", ActiveRecord::Base.connection.quote(value))
          end
        end
      end

      def parse_smart_variables(var, data_source)
        smart_var_data_source =
          ([data_source] + Array(data_source.settings["inherit_smart_settings"]).map { |ds| Blazer.data_sources[ds] }).find { |ds| ds.smart_variables[var] }

        if smart_var_data_source
          query = smart_var_data_source.smart_variables[var]

          if query.is_a? Hash
            smart_var = query.map { |k,v| [v, k] }
          elsif query.is_a? Array
            smart_var = query.map { |v| [v, v] }
          elsif query
            result = smart_var_data_source.run_statement(query)
            smart_var = result.rows.map { |v| v.reverse }
            error = result.error if result.error
          end
        end

        [smart_var, error]
      end

      def variable_params
        params.except(:controller, :action, :id, :host, :query, :dashboard, :query_id, :query_ids, :table_names, :authenticity_token, :utf8, :_method, :commit, :statement, :data_source, :name, :fork_query_id, :blazer, :run_id).permit!
      end
      helper_method :variable_params

      def blazer_user
        send(Blazer.user_method) if Blazer.user_method && respond_to?(Blazer.user_method, true)
      end
      helper_method :blazer_user

      def render_errors(resource)
        @errors = resource.errors
        action = resource.persisted? ? :edit : :new
        render action, status: :unprocessable_entity
      end

      # do not inherit from ApplicationController - #120
      def default_url_options
        {}
      end
  end
end

app/controllers/blazer/checks_controller.rb
module Blazer
  class ChecksController < BaseController
    before_action :set_check, only: [:edit, :update, :destroy, :run]

    def index
      state_order = [nil, "disabled", "error", "timed out", "failing", "passing"]
      @checks = Blazer::Check.joins(:query).includes(:query).order("blazer_queries.name, blazer_checks.id").to_a.sort_by { |q| state_order.index(q.state) || 99 }
      @checks.select! { |c| "#{c.query.name} #{c.emails}".downcase.include?(params[:q]) } if params[:q]
    end

    def new
      @check = Blazer::Check.new(query_id: params[:query_id])
    end

    def create
      @check = Blazer::Check.new(check_params)
      # use creator_id instead of creator
      # since we setup association without checking if column exists
      @check.creator = blazer_user if @check.respond_to?(:creator_id=) && blazer_user

      if @check.save
        redirect_to query_path(@check.query)
      else
        render_errors @check
      end
    end

    def update
      if @check.update(check_params)
        redirect_to query_path(@check.query)
      else
        render_errors @check
      end
    end

    def destroy
      @check.destroy
      redirect_to checks_path
    end

    def run
      @query = @check.query
      redirect_to query_path(@query)
    end

    private

      def check_params
        params.require(:check).permit(:query_id, :emails, :slack_channels, :invert, :check_type, :schedule)
      end

      def set_check
        @check = Blazer::Check.find(params[:id])
      end
  end
end

app/controllers/blazer/dashboards_controller.rb
module Blazer
  class DashboardsController < BaseController
    before_action :set_dashboard, only: [:show, :edit, :update, :destroy, :refresh]

    def new
      @dashboard = Blazer::Dashboard.new
    end

    def create
      @dashboard = Blazer::Dashboard.new
      # use creator_id instead of creator
      # since we setup association without checking if column exists
      @dashboard.creator = blazer_user if @dashboard.respond_to?(:creator_id=) && blazer_user

      if update_dashboard(@dashboard)
        redirect_to dashboard_path(@dashboard)
      else
        render_errors @dashboard
      end
    end

    def show
      @queries = @dashboard.dashboard_queries.order(:position).preload(:query).map(&:query)
      @queries.each do |query|
        process_vars(query.statement, query.data_source)
      end
      @bind_vars ||= []

      @smart_vars = {}
      @sql_errors = []
      @data_sources = @queries.map { |q| Blazer.data_sources[q.data_source] }.uniq
      @bind_vars.each do |var|
        @data_sources.each do |data_source|
          smart_var, error = parse_smart_variables(var, data_source)
          ((@smart_vars[var] ||= []).concat(smart_var)).uniq! if smart_var
          @sql_errors << error if error
        end
      end
    end

    def edit
    end

    def update
      if update_dashboard(@dashboard)
        redirect_to dashboard_path(@dashboard, variable_params)
      else
        render_errors @dashboard
      end
    end

    def destroy
      @dashboard.destroy
      redirect_to dashboards_path
    end

    def refresh
      @dashboard.queries.each do |query|
        data_source = Blazer.data_sources[query.data_source]
        statement = query.statement.dup
        process_vars(statement, query.data_source)
        Blazer.transform_statement.call(data_source, statement) if Blazer.transform_statement
        data_source.clear_cache(statement)
      end
      redirect_to dashboard_path(@dashboard, variable_params)
    end

    private

      def dashboard_params
        params.require(:dashboard).permit(:name)
      end

      def set_dashboard
        @dashboard = Blazer::Dashboard.find(params[:id])
      end

      def update_dashboard(dashboard)
        dashboard.assign_attributes(dashboard_params)
        Blazer::Dashboard.transaction do
          if params[:query_ids].is_a?(Array)
            query_ids = params[:query_ids].map(&:to_i)
            @queries = Blazer::Query.find(query_ids).sort_by { |q| query_ids.index(q.id) }
          end
          if dashboard.save
            if @queries
              @queries.each_with_index do |query, i|
                dashboard_query = dashboard.dashboard_queries.where(query_id: query.id).first_or_initialize
                dashboard_query.position = i
                dashboard_query.save!
              end
              if dashboard.persisted?
                dashboard.dashboard_queries.where.not(query_id: query_ids).destroy_all
              end
            end
            true
          end
        end
      end
  end
end

app/helpers/blazer/base_helper.rb
module Blazer
  module BaseHelper
    def blazer_title(title = nil)
      if title
        content_for(:title) { title }
      else
        content_for?(:title) ? content_for(:title) : nil
      end
    end

    BLAZER_URL_REGEX = /\Ahttps?:\/\/[\S]+\z/
    BLAZER_IMAGE_EXT = %w[png jpg jpeg gif]

    def blazer_format_value(key, value)
      if value.is_a?(Numeric) && !key.to_s.end_with?("id") && !key.to_s.start_with?("id")
        number_with_delimiter(value)
      elsif value.is_a?(String) && value =~ BLAZER_URL_REGEX
        # see if image or link
        if Blazer.images && (key.include?("image") || BLAZER_IMAGE_EXT.include?(value.split(".").last.split("?").first.try(:downcase)))
          link_to value, target: "_blank" do
            image_tag value, referrerpolicy: "no-referrer"
          end
        else
          link_to value, value, target: "_blank"
        end
      else
        value
      end
    end

    def blazer_maps?
      Blazer.mapbox_access_token.present?
    end

    def blazer_js_var(name, value)
      "var #{name} = #{json_escape(value.to_json(root: false))};".html_safe
    end

    def blazer_series_name(k)
      k.nil? ? "null" : k.to_s
    end
  end
end

app/views/blazer/queries/docs.html.erb
<% blazer_title "Docs: #{@data_source.name}" %>

<h1>Docs: <%= @data_source.name %></h1>

<hr />

<h2>Smart Variables</h2>

<% if @smart_variables.any? %>
  <p>Use these variable names to get a dropdown of values.</p>

  <table class="table" style="max-width: 500px;">
    <thead>
      <tr>
        <th>Variable</th>
      </tr>
    </thead>
    <tbody>
      <% @smart_variables.each do |k, _| %>
        <tr>
          <td><code>{<%= k %>}</code></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p>Use <code>{start_time}</code> and <code>{end_time}</code> for a date range selector. End a variable name with <code>_at</code> for a date selector.</p>
<% else %>
  <p>None set - add them in <code>config/blazer.yml</code>.</p>
<% end %>

<h2>Linked Columns</h2>

<% if @linked_columns.any? %>
  <p>Use these column names to link results to other pages.</p>

  <table class="table" style="max-width: 500px;">
    <thead>
      <tr>
        <th style="width: 20%;">Name</th>
        <th>URL</th>
      </tr>
    </thead>
    <tbody>
      <% @linked_columns.each do |k, v| %>
        <tr>
          <td><%= k %></td>
          <td><%= v %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <p>Values that match the format of a URL will be linked automatically.</p>
<% else %>
  <p>None set - add them in <code>config/blazer.yml</code>.</p>
<% end %>

<h2>Smart Columns</h2>

<% if @smart_columns.any? %>
  <p>Use these column names to show additional data.</p>

  <table class="table" style="max-width: 500px;">
    <thead>
      <tr>
        <th>Name</th>
      </tr>
    </thead>
    <tbody>
      <% @smart_columns.each do |k, _| %>
        <tr>
          <td><%= k %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>None set - add them in <code>config/blazer.yml</code>.</p>
<% end %>

<h2>Charts</h2>

<p>Use specific combinations of column types to generate charts.</p>

<table class="table" style="max-width: 500px;">
  <thead>
    <tr>
      <th style="width: 20%;">Chart</th>
      <th>Column Types</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Line</td>
      <td>2+ columns - timestamp, numeric(s)</td>
    </tr>
    <tr>
      <td>Line</td>
      <td>3 columns - timestamp, string, numeric</td>
    </tr>
    <tr>
      <td>Column</td>
      <td>2+ columns - string, numeric(s)</td>
    </tr>
    <tr>
      <td>Column</td>
      <td>3 columns - string, string, numeric</td>
    </tr>
    <tr>
      <td>Scatter</td>
      <td>2 columns - both numeric</td>
    </tr>
    <tr>
      <td>Pie</td>
      <td>2 columns - string, numeric - and last column named <code>pie</code></td>
    </tr>
    <tr>
      <td>Map</td>
      <td>
        Named <code>latitude</code> and <code>longitude</code>, or <code>lat</code> and <code>lon</code>, or <code>lat</code> and <code>lng</code>
        <% if !blazer_maps? %>
          <br />
          <strong>Needs configured</strong>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

<p>Use the column name <code>target</code> to draw a line for goals.</p>

app/views/blazer/queries/edit.html.erb
<% blazer_title "Edit - #{@query.name}" %>
<%= render partial: "form" %>

app/views/blazer/queries/home.html.erb
<div id="queries" class="row m-1 p-1 border-bottom">
  <div class="col-md-8">
    <input type="text" v-model="searchTerm" placeholder="Start typing a query, dashboard, or person" v-focus class="search form-control" />
  </div>
  <div id="header" class="col-md-4 pr-0 text-right">
    <div>
      <% if blazer_user %>
        <%= link_to "All", root_path, class: "m-1 #{!params[:filter] ? "active" : nil}" %>

        <% if Blazer.audit %>
          <%= link_to "Viewed", root_path(filter: "viewed"), class: "m-1 #{params[:filter] == "viewed" ? "active" : nil}" %>
        <% end %>

        <%= link_to "Mine", root_path(filter: "mine"), class: "m-1 #{params[:filter] == "mine" ? "active" : nil}" %>
      <% end %>

      <div class="btn-group">
        <%= link_to "New Query", new_query_path, class: "btn btn-info" %>
        <button type="button" class="btn btn-info dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="caret"></span>
          <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu">
          <li><%= link_to "Checks", checks_path, class: "dropdown-item" %></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "New Dashboard", new_dashboard_path, class: "dropdown-item" %></li>
          <li><%= link_to "New Check", new_check_path, class: "dropdown-item" %></li>
        </ul>
      </div>
    </div>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <% if Blazer.user_class %>
          <th>Mastermind</th>
        <% end%>
      </tr>
    </thead>
    <tbody class="list" v-cloak>
      <tr v-for="query in visibleItems">
        <td>
          <a :href="itemPath(query)" :class="{ dashboard: query.dashboard }">{{ query.name }}</a>
          <span class="vars">{{ query.vars }}</span>
        </td>
        <% if Blazer.user_class %>
          <td class="creator">{{ query.creator }}</td>
        <% end %>
      </tr>
    </tbody>
  </table>

  <p v-if="more" class="text-muted">Loading...</p>
</div>

<script>
  <%= blazer_js_var "dashboards", @dashboards %>
  <%= blazer_js_var "queries", @queries %>
  <%= blazer_js_var "more", @more %>

  var prepareSearch = function (list) {
    var i, q, searchStr
    for (i = 0; i < list.length; i++) {
      q = list[i]
      searchStr = q.name + q.creator
      if (q.creator === "You") {
        searchStr += "mine me"
      }
      q.searchStr = prepareQuery(searchStr)
    }
  }

  var prepareQuery = function (str) {
    return str.toLowerCase().replace(/\W+/g, "")
  }

  var app = new Vue({
    el: "#queries",
    data: {
      searchTerm: "",
      more: more,
      updateCounter: 0
    },
    created: function() {
      this.listItems = dashboards.concat(queries)

      prepareSearch(this.listItems)

      this.queryIds = {}
      for (i = 0; i < queries.length; i++) {
        this.queryIds[queries[i].id] = true
      }

      if (this.more) {
        var _this = this

        $.getJSON(Routes.queries_path(), function (data) {
          var i, j, newValues, val, size = 500;

          var newValues = []
          for (j = 0; j < data.length; j++) {
            val = data[j]
            if (val && !_this.queryIds[val.id]) {
              newValues.push(val)
            }
          }

          prepareSearch(newValues)

          _this.listItems = _this.listItems.concat(newValues)
          _this.more = false
          // hack to get to update
          _this.updateCounter++
        })
      }
    },
    computed: {
      visibleItems: function () {
        // hack to get to update
        this.updateCounter

        var pageSize = 200
        var q, i

        if (this.searchTerm.length > 0) {
          var term = prepareQuery(this.searchTerm)
          var items = []
          var fuzzyItems = []
          for (i = 0; i < this.listItems.length; i++) {
            q = this.listItems[i]
            if (q.searchStr.indexOf(term) !== -1) {
              items.push(q)
              if (items.length == pageSize) {
                break
              }
            } else if (fuzzysearch(term, q.searchStr)) {
              fuzzyItems.push(q)
            }
          }
          return items.concat(fuzzyItems).slice(0, pageSize)
        } else {
          return this.listItems.slice(0, pageSize)
        }
      }
    },
    methods: {
      itemPath: function (item) {
        if (item.dashboard) {
          return Routes.dashboard_path(item.to_param)
        } else {
          return Routes.query_path(item.to_param)
        }
      }
    },
    directives: {
      focus: {
        inserted: function (el) {
          el.focus()
        }
      }
    }
  })
</script>

app/views/blazer/queries/new.html.erb
<% blazer_title "New Query" %>
<%= render partial: "form" %>

app/views/blazer/queries/schema.html.erb
<% blazer_title "Schema: #{@data_source.name}" %>

<h1>Schema: <%= @data_source.name %></h1>

<hr />

<div id="header">
  <input id="search" type="text" placeholder="Start typing a table or column" class="search form-control" />
</div>

<% @schema.each do |table| %>
  <table class="table schema-table">
    <thead>
      <tr>
        <th colspan="2">
          <% if table[:schema] != "public" %><%= table[:schema] %>.<% end %><%= table[:table] %>
        </th>
      </tr>
    </thead>
    <tbody>
      <% table[:columns].each do |column| %>
        <tr>
          <td><%= column[:name] %></td>
          <td class="text-muted"><%= column[:data_type] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<script>
  $("#search").on("keyup", function() {
    var value = $(this).val().toLowerCase()
    $(".schema-table").filter(function() {
      // if found in table name, show entire table
      // if just found in rows, show row

      var found = $(this).find("thead").text().toLowerCase().indexOf(value) > -1

      if (found) {
        $(this).find("tbody tr").toggle(true)
      } else {
        $(this).find("tbody tr").filter(function() {
          var found2 = $(this).text().toLowerCase().indexOf(value) > -1
          $(this).toggle(found2)
          if (found2) {
            found = true
          }
        })
      }

      $(this).toggle(found)
    })
  }).focus()
</script>

app/views/blazer/queries/show.html.erb
<% blazer_title @query.name %>

<div class="topbar m-1 p-1 border-bottom">
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2 pl-0">
        <%= render partial: "blazer/nav" %>
      </div>
      <div class="col-sm-7 text-center">
        <h3 class="m-0">
          <%= @query.name %>
        </h3>
      </div>
      <div class="col-sm-3 text-right pr-0">
        <%= link_to "Edit", edit_query_path(@query, variable_params), class: "btn btn-default", disabled: !@query.editable?(blazer_user) %>
        <%= link_to "Fork", new_query_path(variable_params.merge(fork_query_id: @query.id, data_source: @query.data_source, name: @query.name)), class: "btn btn-info" %>

        <% if !@error && @success %>
          <%= button_to "Download", run_queries_path(query_id: @query.id, format: "csv", forecast: params[:forecast]), params: {statement: @statement}, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="mb-5"></div>

<% if @sql_errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @sql_errors.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if @query.description.present? %>
  <p><%= @query.description %></p>
<% end %>

<%= render partial: "blazer/variables", locals: {action: query_path(@query)} %>

<pre id="code"><code><%= @statement %></code></pre>

<% if @success %>
  <div id="results">
    <p class="text-muted">Loading...</p>
  </div>

  <script>
    function showRun(data) {
      $("#results").html(data)
      $("#results table").stupidtable(stupidtableCustomSettings).stickyTableHeaders({fixedOffset: 60})
    }

    function showError(message) {
      $("#results").addClass("query-error").html(message)
    }

    <%= blazer_js_var "data", variable_params.merge(statement: @statement, query_id: @query.id, data_source: @query.data_source) %>

    runQuery(data, showRun, showError)
  </script>
<% end %>

<% unless %w(mongodb).include?(Blazer.data_sources[@query.data_source].adapter) %>
  <script>
    // do not highlight really long queries
    // this can lead to performance issues
    if ($("code").text().length < 10000) {
      hljs.highlightBlock(document.getElementById("code"));
    }
  </script>
<% end %>